#!/usr/bin/env python
"""
Materialize a reboot-v2 VDS/sharded dataset into one physical HDF5 file.

Input:
- VDS file generated by rebuild_reboot_v2_from_npz_pool.py
- Shard directory containing per-file reboot-v2 shards

Output:
- A single physical HDF5 with reboot-v2 datasets.
"""

from __future__ import annotations

import argparse
import logging
from pathlib import Path
from typing import Dict, List, Tuple

import h5py
import numpy as np
from tqdm import tqdm


log = logging.getLogger("materialize_reboot_v2_vds_to_hdf5")

DATASET_KEYS = [
    "action",
    "state",
    "cmd",
    "state_hist",
    "cmd_hist",
    "state_delta",
    "recovery_flag",
]


def _resolve_compression(name: str, level: int):
    if name == "none":
        return None, None
    if name == "lzf":
        return "lzf", None
    return "gzip", int(level)


def _decode_strs(arr: np.ndarray) -> List[str]:
    out: List[str] = []
    for x in arr:
        if isinstance(x, (bytes, np.bytes_)):
            out.append(x.decode("utf-8"))
        else:
            out.append(str(x))
    return out


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Materialize reboot-v2 VDS+shards into one physical HDF5 file."
    )
    parser.add_argument("--input_vds_hdf5", type=str, required=True)
    parser.add_argument("--shard_dir", type=str, required=True)
    parser.add_argument("--output_hdf5", type=str, required=True)
    parser.add_argument("--chunk_size", type=int, default=8192)
    parser.add_argument("--compression", type=str, default="gzip", choices=["gzip", "lzf", "none"])
    parser.add_argument("--compression_level", type=int, default=1)
    parser.add_argument("--overwrite", action="store_true")
    return parser.parse_args()


def _resolve_shard_paths(vds: h5py.File, shard_dir: Path) -> List[Path]:
    if "file_names" not in vds:
        raise KeyError("Missing file_names in VDS.")
    file_names = _decode_strs(np.asarray(vds["file_names"][:]))
    expected = [shard_dir / f"{Path(name).stem}.reboot_v2.hdf5" for name in file_names]
    if all(p.is_file() for p in expected):
        return expected

    if "shard_paths" in vds:
        fallback = [Path(p) for p in _decode_strs(np.asarray(vds["shard_paths"][:]))]
        if all(p.is_file() for p in fallback):
            return fallback

    missing = [str(p) for p in expected if not p.is_file()]
    raise FileNotFoundError(
        "Unable to resolve shard files from shard_dir or shard_paths; "
        f"missing examples: {missing[:3]}"
    )


def _copy_attrs(src: h5py.File, dst: h5py.File) -> None:
    for key, value in src.attrs.items():
        # This output is materialized physical data.
        if key == "vds":
            continue
        dst.attrs[key] = value
    dst.attrs["materialized_from_vds"] = True


def main() -> None:
    args = _parse_args()
    logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")

    input_vds = Path(args.input_vds_hdf5).expanduser().resolve()
    shard_dir = Path(args.shard_dir).expanduser().resolve()
    output_hdf5 = Path(args.output_hdf5).expanduser().resolve()

    if not input_vds.is_file():
        raise FileNotFoundError(f"Input VDS not found: {input_vds}")
    if not shard_dir.is_dir():
        raise FileNotFoundError(f"Shard dir not found: {shard_dir}")
    if output_hdf5.exists():
        if args.overwrite:
            output_hdf5.unlink()
        else:
            raise FileExistsError(f"Output exists: {output_hdf5}; pass --overwrite")
    output_hdf5.parent.mkdir(parents=True, exist_ok=True)

    comp, comp_opts = _resolve_compression(args.compression, args.compression_level)

    with h5py.File(input_vds, "r") as fv:
        for key in DATASET_KEYS:
            if key not in fv:
                raise KeyError(f"Missing dataset in VDS: {key}")
        if "file_offsets" not in fv or "file_names" not in fv:
            raise KeyError("VDS missing file_offsets/file_names.")

        total_samples = int(fv.attrs.get("num_samples", fv["state"].shape[0]))
        shard_paths = _resolve_shard_paths(fv, shard_dir)
        file_offsets = np.asarray(fv["file_offsets"][:], dtype=np.int64)
        file_names = np.asarray(fv["file_names"][:])

        layouts: Dict[str, Tuple[Tuple[int, ...], np.dtype]] = {}
        for key in DATASET_KEYS:
            ds = fv[key]
            if int(ds.shape[0]) != total_samples:
                raise ValueError(f"Dataset sample mismatch for {key}: {ds.shape[0]} vs {total_samples}")
            layouts[key] = (tuple(ds.shape[1:]), np.dtype(ds.dtype))

        with h5py.File(output_hdf5, "w") as fo:
            _copy_attrs(fv, fo)
            fo.attrs["source_vds_hdf5"] = str(input_vds)
            fo.attrs["source_shard_dir"] = str(shard_dir)

            out_ds: Dict[str, h5py.Dataset] = {}
            for key in DATASET_KEYS:
                tail, dtype = layouts[key]
                chunk = (min(max(1, args.chunk_size), total_samples),) + tail
                out_ds[key] = fo.create_dataset(
                    key,
                    shape=(total_samples,) + tail,
                    dtype=dtype,
                    chunks=chunk,
                    compression=comp,
                    compression_opts=comp_opts,
                )

            fo.create_dataset("file_offsets", data=file_offsets)
            fo.create_dataset("file_names", data=file_names)

            cursor = 0
            for shard_path in tqdm(shard_paths, desc="Materializing shards"):
                with h5py.File(shard_path, "r") as fs:
                    n = int(fs["state"].shape[0])
                    for key in DATASET_KEYS:
                        if key not in fs:
                            raise KeyError(f"Missing dataset {key} in shard {shard_path}")

                    for start in range(0, n, int(args.chunk_size)):
                        end = min(start + int(args.chunk_size), n)
                        out_slice = slice(cursor + start, cursor + end)
                        src_slice = slice(start, end)
                        for key in DATASET_KEYS:
                            out_ds[key][out_slice] = fs[key][src_slice]

                cursor += n

            if cursor != total_samples:
                raise ValueError(f"Copied samples mismatch: cursor={cursor}, total={total_samples}")

    with h5py.File(output_hdf5, "r") as fchk:
        log.info("Wrote output: %s", output_hdf5)
        log.info("num_samples=%d", int(fchk.attrs.get("num_samples", -1)))
        for key in DATASET_KEYS:
            log.info("%s %s %s", key, str(fchk[key].shape), str(fchk[key].dtype))


if __name__ == "__main__":
    main()
